# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200

checkpoint:
  save_interval_updates: 20000
  keep_interval_updates: 10
  no_epoch_checkpoints: true

task:
  _name: audio_pretraining
  data: ???
  max_sample_size: 6000
  min_sample_size: 1000
  normalize: false
  sample_rate: 100

dataset:
  num_workers: 16
  max_tokens: 12000
  # batch_size: 1
  skip_invalid_size_inputs_valid_test: true

distributed_training:
  distributed_world_size: 1
  ddp_backend: legacy_ddp
  # device_id:

criterion:
  _name: wav2vec
  infonce: true
  log_keys: ["prob_perplexity","code_perplexity","temp"]
  loss_weights: [0.1, 10]

optimization:
  max_update: 400000
  lr: [0.0005]
  update_freq: [64]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.01

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 32000

model:
  _name: wav2vec2
  quantize_targets: true
  final_dim: 128
  encoder_layerdrop: 0
  dropout_input: 0
  dropout_features: 0
  feature_grad_mult: 0
  encoder_embed_dim: 128
  encoder_ffn_embed_dim: 256
  encoder_attention_heads: 4